//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEFTHost.FeftServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEFTResponse", Namespace="http://schemas.datacontract.org/2004/07/FEFTRest")]
    [System.SerializableAttribute()]
    public partial class FEFTResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cashBackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string midField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string panField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rrnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.authCodeField, value) != true)) {
                    this.authCodeField = value;
                    this.RaisePropertyChanged("authCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardExpiry {
            get {
                return this.cardExpiryField;
            }
            set {
                if ((object.ReferenceEquals(this.cardExpiryField, value) != true)) {
                    this.cardExpiryField = value;
                    this.RaisePropertyChanged("cardExpiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cashBack {
            get {
                return this.cashBackField;
            }
            set {
                if ((object.ReferenceEquals(this.cashBackField, value) != true)) {
                    this.cashBackField = value;
                    this.RaisePropertyChanged("cashBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceNoField, value) != true)) {
                    this.invoiceNoField = value;
                    this.RaisePropertyChanged("invoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mid {
            get {
                return this.midField;
            }
            set {
                if ((object.ReferenceEquals(this.midField, value) != true)) {
                    this.midField = value;
                    this.RaisePropertyChanged("mid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pan {
            get {
                return this.panField;
            }
            set {
                if ((object.ReferenceEquals(this.panField, value) != true)) {
                    this.panField = value;
                    this.RaisePropertyChanged("pan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentDetails {
            get {
                return this.paymentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentDetailsField, value) != true)) {
                    this.paymentDetailsField = value;
                    this.RaisePropertyChanged("paymentDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.respCodeField, value) != true)) {
                    this.respCodeField = value;
                    this.RaisePropertyChanged("respCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                if ((object.ReferenceEquals(this.rrnField, value) != true)) {
                    this.rrnField = value;
                    this.RaisePropertyChanged("rrn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                if ((object.ReferenceEquals(this.tidField, value) != true)) {
                    this.tidField = value;
                    this.RaisePropertyChanged("tid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionTypeField, value) != true)) {
                    this.transactionTypeField = value;
                    this.RaisePropertyChanged("transactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleRequest", Namespace="http://schemas.datacontract.org/2004/07/FEFTRest")]
    [System.SerializableAttribute()]
    public partial class SaleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashBackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TillNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashBack {
            get {
                return this.CashBackField;
            }
            set {
                if ((object.ReferenceEquals(this.CashBackField, value) != true)) {
                    this.CashBackField = value;
                    this.RaisePropertyChanged("CashBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TillNO {
            get {
                return this.TillNOField;
            }
            set {
                if ((object.ReferenceEquals(this.TillNOField, value) != true)) {
                    this.TillNOField = value;
                    this.RaisePropertyChanged("TillNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransKey {
            get {
                return this.TransKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TransKeyField, value) != true)) {
                    this.TransKeyField = value;
                    this.RaisePropertyChanged("TransKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReversalRequest", Namespace="http://schemas.datacontract.org/2004/07/FEFTRest")]
    [System.SerializableAttribute()]
    public partial class ReversalRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransKey {
            get {
                return this.TransKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TransKeyField, value) != true)) {
                    this.TransKeyField = value;
                    this.RaisePropertyChanged("TransKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeftServiceReference.IFEFTService")]
    public interface IFEFTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEFTService/sale", ReplyAction="http://tempuri.org/IFEFTService/saleResponse")]
        FEFTHost.FeftServiceReference.FEFTResponse sale(string transKey, string Bank, string amount, string cashBack, string tillNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEFTService/reversal", ReplyAction="http://tempuri.org/IFEFTService/reversalResponse")]
        FEFTHost.FeftServiceReference.FEFTResponse reversal(string TransKey, string Bank, string Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEFTService/execSale", ReplyAction="http://tempuri.org/IFEFTService/execSaleResponse")]
        FEFTHost.FeftServiceReference.FEFTResponse execSale(FEFTHost.FeftServiceReference.SaleRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFEFTService/execReversal", ReplyAction="http://tempuri.org/IFEFTService/execReversalResponse")]
        FEFTHost.FeftServiceReference.FEFTResponse execReversal(FEFTHost.FeftServiceReference.ReversalRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFEFTServiceChannel : FEFTHost.FeftServiceReference.IFEFTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FEFTServiceClient : System.ServiceModel.ClientBase<FEFTHost.FeftServiceReference.IFEFTService>, FEFTHost.FeftServiceReference.IFEFTService {
        
        public FEFTServiceClient() {
        }
        
        public FEFTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FEFTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FEFTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FEFTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FEFTHost.FeftServiceReference.FEFTResponse sale(string transKey, string Bank, string amount, string cashBack, string tillNO) {
            return base.Channel.sale(transKey, Bank, amount, cashBack, tillNO);
        }
        
        public FEFTHost.FeftServiceReference.FEFTResponse reversal(string TransKey, string Bank, string Amount) {
            return base.Channel.reversal(TransKey, Bank, Amount);
        }
        
        public FEFTHost.FeftServiceReference.FEFTResponse execSale(FEFTHost.FeftServiceReference.SaleRequest req) {
            return base.Channel.execSale(req);
        }
        
        public FEFTHost.FeftServiceReference.FEFTResponse execReversal(FEFTHost.FeftServiceReference.ReversalRequest req) {
            return base.Channel.execReversal(req);
        }
    }
}
